### ISSUE TITLE
Fixed github issue title header overlaps the reaction nav

### ISSUE THREAD

**Issue by dmstern** [NorfeldtAbtion/github-issue-reactions-browser-extension#4]
**IS:**

![image](https://user-images.githubusercontent.com/5219707/73728322-6f093500-4733-11ea-838a-c96b681ab510.png)

**SHOULD:**

![image](https://user-images.githubusercontent.com/5219707/73728937-7e3cb280-4734-11ea-96f7-9323fbf3179d.png)

**Comment by NorfeldtAbtion** [comment]
#3 should fix it (thanks @JuhG )

I believe that the github sticky header is some A/B testing because I don't have it but some of my colleagues have it.
