### ISSUE TITLE
Works in Brave?

### ISSUE THREAD

**Issue by danawoodman** [NorfeldtAbtion/github-issue-reactions-browser-extension#7]
I've followed the Chrome extensions in the Brave browser but am not seeing the extension even after reloading

![image](https://user-images.githubusercontent.com/157695/107858123-5ff9a000-6de7-11eb-869e-7184b984fb21.png)

I've restarted Brave and reloaded the extension.

I've also disabled "shields" for Github.com.

EDIT: Noticed this, which seems wrong? 

![image](https://user-images.githubusercontent.com/157695/107858254-2aa18200-6de8-11eb-9aaf-c75e06fc2a42.png)

**Comment by Norfeldt** [comment]
I don't have any experience with Brave. But browsing on the topic I saw that it can install chrome extensions from the chrome webstore - so it should be able to work.

What errors shows when you click the errors button?

It could be something with a missing manifest - which states what this extension needs access to.

**Comment by danawoodman** [comment]
@Norfeldt thanks for the reply, actually it was this line:

```js
header.style = position: relative;height: 100%;`;
```

Which I fixed by turning into a string but it's still not loading properly. I'll try to debug it a bit more myself and report back 👍

**Comment by danawoodman** [comment]
Ah, i think I assumed it also works for Pull Request which is what I was viewing. Issues do seem to work 😄  Maybe I'll submit a PR for PR support 😉

**Comment by danawoodman** [comment]
Added PR #8 to add Pull Request support and a few other tweaks

**Comment by Norfeldt** [comment]
I have merged #8 - thank you

**Comment by danawoodman** [comment]
Thank you @Norfeldt for the extension and the merge!
